#!/bin/sh

ROOT=$(realpath $(dirname $0)/..)
FORCH_ROOT=$ROOT
DAQ_ROOT=$ROOT/daq
FAUCET_ROOT=$ROOT/faucet

# User might already exist if docker restarted.
echo "kronkiteman::$USERID:$USERID::/:bin/bash" >> /etc/passwd

sudo -u kronkiteman \
    FAUCET_EXCEPTION_LOG=/var/log/faucet_br/faucet_exception.log \
    FAUCET_CONFIG_STAT_RELOAD=1 FAUCET_RYU_CONF=/etc/faucet_br/ryu.conf \
    FAUCET_LISTEN_PORT=3984 FAUCET_PROMETHEUS_PORT=5678 \
    FAUCET_CONFIG=/etc/faucet_br/faucet.yaml FAUCET_LOG=/var/log/faucet_br/faucet.log \
    FAUCET_EVENT_SOCK=/var/log/faucet_br/faucet_event.sock WSAPI_LISTEN_PORT=4567 \
    faucet --ryu-config-file=/etc/faucet_br/ryu.conf --ryu-ofp-tcp-listen-port=3984 &
sudo -u kronkiteman \
     FAUCET_EVENT_SOCK=$FAUCET_EVENT_SOCK \
     FAUCET_EVENT_SOCK_HEARTBEAT=$FAUCET_EVENT_SOCK_HEARTBEAT \
     FAUCET_CONFIG_STAT_RELOAD=$FAUCET_CONFIG_STAT_RELOAD \
     FAUCET_CONFIG=$FAUCET_CONFIG \
     faucet --ryu-config-file=${FAUCET_RYU_CONF} --ryu-ofp-tcp-listen-port=${FAUCET_LISTEN_PORT} &


echo Adding fot bridge
sudo /usr/share/openvswitch/scripts/ovs-ctl start
sudo ovs-vsctl --if-exists del-br br-fot \
    -- add-br br-fot \
    -- set-fail-mode br-fot secure \
    -- set bridge br-fot other_config:datapath-id=0xfa
echo Adding fot bridge controller
sudo ovs-vsctl set-controller br-fot tcp:127.0.0.1:3984
/usr/bin/gauge_go &
/usr/bin/forch &
while ! ip link show data0; do
    sleep 2
done

echo Adding fot bridge port
sudo ovs-vsctl add-port br-fot data0 -- set interface data0 ofport_request=1
ifconfig data0 up

echo Starting daq...
PYTHONPATH=$DAQ_ROOT:$FORCH_ROOT:$FAUCET_ROOT:$DAQ_ROOT/mininet:$DAQ_ROOT/libs:$DAQ_ROOT/libs/proto
sudo \
    PYTHONPATH=$PYTHONPATH \
    PATH=$DAQ_ROOT/mininet:$PATH \
    daq/cmd/start ../bin/daq_config.yaml &

echo Blocking forever...
tail -f /dev/null
