---
linters:
  flake8:
    python: 3
    max-line-length: 100
  pep8:
    python: 3
    max-line-length: 100
  py3k:
    ignore:
      - 'W1618'
      - 'W1619'
      - 'E1601'
files:
  ignore:
    - 'forch/proto/*'
