# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from forch.proto import devices_state_pb2 as forch_dot_proto_dot_devices__state__pb2
from forch.proto import shared_constants_pb2 as forch_dot_proto_dot_shared__constants__pb2


class DeviceReportStub(object):
    """
    gRPC service to receive testing results
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportDevicesState = channel.unary_unary(
                '/DeviceReport/ReportDevicesState',
                request_serializer=forch_dot_proto_dot_devices__state__pb2.DevicesState.SerializeToString,
                response_deserializer=forch_dot_proto_dot_shared__constants__pb2.Empty.FromString,
                )
        self.GetPortState = channel.unary_stream(
                '/DeviceReport/GetPortState',
                request_serializer=forch_dot_proto_dot_devices__state__pb2.Device.SerializeToString,
                response_deserializer=forch_dot_proto_dot_devices__state__pb2.DevicePortEvent.FromString,
                )


class DeviceReportServicer(object):
    """
    gRPC service to receive testing results
    """

    def ReportDevicesState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceReportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportDevicesState': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportDevicesState,
                    request_deserializer=forch_dot_proto_dot_devices__state__pb2.DevicesState.FromString,
                    response_serializer=forch_dot_proto_dot_shared__constants__pb2.Empty.SerializeToString,
            ),
            'GetPortState': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPortState,
                    request_deserializer=forch_dot_proto_dot_devices__state__pb2.Device.FromString,
                    response_serializer=forch_dot_proto_dot_devices__state__pb2.DevicePortEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DeviceReport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeviceReport(object):
    """
    gRPC service to receive testing results
    """

    @staticmethod
    def ReportDevicesState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DeviceReport/ReportDevicesState',
            forch_dot_proto_dot_devices__state__pb2.DevicesState.SerializeToString,
            forch_dot_proto_dot_shared__constants__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPortState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/DeviceReport/GetPortState',
            forch_dot_proto_dot_devices__state__pb2.Device.SerializeToString,
            forch_dot_proto_dot_devices__state__pb2.DevicePortEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
