#!/bin/bash -e

ROOT=$(realpath $(dirname $0)/..)
PREFIX=
PYTHON=python3
EXTARGS=
coverage=

if [ "$1" == coverage ]; then
    coverage=y
    PYTHON=coverage3
    EXTARGS="run --source $ROOT/forch"
    shift
fi

if [ $# == 0 ]; then
    echo $0 test_name [class_name]
    echo class_name should be the unit test class with an optional method name e.g. FotFaucetizerTestCase.test_device_states 
    false
fi

TEST_NAME=$1
CLASS_NAME=$2
shift

TEST_DIR=testing/python_lib
TEST_SRC=$TEST_NAME.py
export PYTHONPATH=$ROOT/testing:$ROOT

if [ -z "$VIRTUAL_ENV" -a -f venv/bin/$PYTHON ]; then
    PYTHON=venv/bin/$PYTHON
fi

cd $ROOT

if [ -n "$coverage" ]; then
    $PYTHON erase
fi

$PYTHON $EXTARGS $TEST_DIR/$TEST_SRC $CLASS_NAME

if [ -n "$coverage" ]; then
    $PYTHON combine || true
    $PYTHON report -m
fi

