#!/bin/bash -e

if [ $# != 1 ]; then
    echo $0 [test_dir]
    false
fi

ROOT=$(realpath $(dirname $0)/..)
TEST_DIR=testing/$1
PYTHONPATH=$ROOT/testing:$ROOT

export PYTHONPATH

if [ -z "$VIRTUAL_ENV" -a -f venv/bin/python3 ]; then
    PYTHON=venv/bin/python3
else
    PYTHON=python3
fi

cd $ROOT
$PYTHON -m unittest discover \
    -s $TEST_DIR \
    -p "test_*.py"
