#!/bin/bash -e

source bin/stack_functions

preamble_setup

function report_vlans {
    $YQ '.dps."nz-kiwi-t2sw1".interfaces."1".native_vlan' $BEHAVIORAL_CONFIG | tee -a $TEST_RESULTS
    $YQ '.dps."nz-kiwi-t2sw1".interfaces."4".native_vlan' $BEHAVIORAL_CONFIG | tee -a $TEST_RESULTS
    $YQ '.dps."nz-kiwi-t2sw1".interfaces."5".native_vlan' $BEHAVIORAL_CONFIG | tee -a $TEST_RESULTS
    $YQ '.dps."nz-kiwi-t2sw2".interfaces."1".native_vlan' $BEHAVIORAL_CONFIG | tee -a $TEST_RESULTS
    $YQ '.dps."nz-kiwi-t2sw3".interfaces."1".native_vlan' $BEHAVIORAL_CONFIG | tee -a $TEST_RESULTS
}

if [ -f inst/forch-controller-1/daq/inst/cmdrun.log ]; then
    DAQ_BASE=inst/forch-controller-1/daq/inst
elif [ -f inst/forch-dts/cmdrun.log ]; then
    DAQ_BASE=inst/forch-dts/
else
    echo Could not find cmdrun.log file.
    false
fi

INST_BASE=inst/forch-controller-1
FAUCET_BASE=$INST_BASE/faucet
BEHAVIORAL_CONFIG=$FAUCET_BASE/faucet.yaml
YQ=venv/bin/yq

echo `timestamp` DAQ spot checks
# faux-1: tests passing, moved to operational
# faux-2: tests failing, moved to infracted
# faux-3: device removed, testing cancelled
# faux-4: static behavior, scheduled testing in 20s
# faux-5: tests timeout (hold test enabled)

# Test that no-sequester works
docker exec forch-faux-4 ping -c 10 192.168.1.0
# Schedule testing for faux-4 in 20s
timestamp=`python3 -c "import datetime; print((datetime.datetime.now() + datetime.timedelta(seconds=20)).isoformat())"`
docker exec forch-controller-1 bash -c "sed -i \"s/REPLACE_WITH_TIMESTAMP/$timestamp/\" /etc/forch/behaviors.yaml && touch /etc/forch/behaviors.yaml"

# Ongoing activity faux-5 to keep it learned
docker exec forch-faux-5 ping -c 1000 192.168.1.0 > /dev/null &

echo Tail of DAQ log
tail $DAQ_BASE/cmdrun.log || true

# Basic process startup.
echo Check basic process startup
fgrep "Loading base module config" $DAQ_BASE/cmdrun.log

# Testing that python path is good.
ls -l $DAQ_BASE/daq.pid

# Requires valid config available.
cat $DAQ_BASE/daq_run_id.txt

# Requiring mininet path.
ls -l $DAQ_BASE/dp_port_acls.yaml

# Check that OVS switch connects properly to managed faucet.
echo Check for managed faucet
fgrep "System port 1 on dpid 1 is active True" $DAQ_BASE/cmdrun.log

echo Done with daq startup tests.

# Forch startup checks
# Check Forch has successfuly started
fgrep -o "Starting Forchestrator" $INST_BASE/forch.log | tee -a $TEST_RESULTS

# Waiting for DAQ test to complete
monitor_daq_log "Setting port set 1 to vlan 27[0-9]"
monitor_daq_log "Setting port set 2 to vlan 27[0-9]"

docker exec forch-faux-1 ip addr show faux-eth0 | grep inet
docker exec forch-faux-2 ip addr show faux-eth0 | grep inet

vlan=$($YQ '.dps."nz-kiwi-t2sw1".interfaces."1".native_vlan' $BEHAVIORAL_CONFIG)
echo $(( (vlan > 271) + (vlan > 276) )) | tee -a $TEST_RESULTS
echo $(( (vlan > 271) + (vlan > 276) )) | tee -a $TEST_RESULTS

monitor_daq_log "Send device result 9a:99:57:1e:8f:01 passed"
monitor_daq_log "Send device result 9a:99:57:1e:8f:02 failed"
monitor_daq_log "Target device 9a99571e8f03 test hold running"
monitor_daq_log "Target device 9a99571e8f05 test hold running"

echo `timestamp` stopping forch-faux-3
docker stop forch-faux-3 # Remove device 3 to generate port-down event.

report_vlans

monitor_forch_log "Device 9a:99:57:1e:8f:04 is entering operational state from unauthenticated state"

# Check if it's running in client/server or server/client mode and adjust expectations accordingly.
sserv_mode=$(fgrep ssserv $DAQ_BASE/cmdrun.log | wc -l)
if [[ $sserv_mode == 0 ]]; then
    monitor_daq_log "Remaining target sets: \[9a99571e8f05\]"
    expected_timeouts=0
    # Device 8f:05 doesn't timeout in this mode, so add artificial result for later on.
    echo "9a99571e8f05: ['9a99571e8f05:hold:DaqException']" | sudo tee -a $DAQ_BASE/result.log
else
    monitor_forch_log "Device 9a:99:57:1e:8f:03 disconnected"
    monitor_daq_log "Remaining target sets: \[\]"
    expected_timeouts=2
fi

sequester_timeouts=$(egrep "Handle device .* sequester timeout" $INST_BASE/forch.log | wc -l)
echo `timestamp` Found $sequester_timeouts and expected $expected_timeouts
[[ $sequester_timeouts == $expected_timeouts ]]

cat $DAQ_BASE/result.log | sort | tee -a $TEST_RESULTS
docker exec forch-faux-1 ping -c 5 192.168.1.0  > /dev/null # Make tests less flaky
docker exec forch-faux-1 ping -c 5 192.168.1.0 | fgrep "packet loss" | redact | tee -a $TEST_RESULTS
docker exec forch-faux-2 ping -c 5 192.168.1.0 | fgrep "packet loss" | redact | tee -a $TEST_RESULTS

# Check to make sure allocated interfaces are cleaned up properly.
fgrep "Configured topology with" $DAQ_BASE/cmdrun.log | tail -n 1 | sed 's/.*INFO/X/' | tee -a $TEST_RESULTS

echo Remaining vxlan interfaces:
docker exec forch-controller-1 ip link | fgrep vxlan | tee -a $TEST_RESULT

faucet_lc=$(cat $INST_BASE/faucet.log | wc -l)
forch_lc=$(cat $INST_BASE/forch.log | wc -l)
daq_lc=$(cat $DAQ_BASE/cmdrun.log | wc -l)
echo Log line lengths: faucet $faucet_lc forch $forch_lc daq $daq_lc

# TODO: Actually validate this with tests to detect learning loops. Currently very flaky.
echo Log line lengths: $((faucet_lc < 4500)) $((forch_lc < 2000)) $((daq_lc < 1500))

echo `timestamp` Done with test_fot
