#!/bin/bash -e

source bin/stack_functions

preamble_setup

export TEST_RESULTS

# These two tests below could be run as their own test shards, if desired.
testing/test_basics
testing/test_topology

# Run unit tests
testing/test_unit
