#!/bin/bash -ex

INST_BASE=inst/forch-controller-1
DAQBASE=$INST_BASE/daq
FAUCET_BASE=$INST_BASE/faucet
BEHAVIORAL_CONFIG=$FAUCET_BASE/faucet.yaml

echo Controller startup log
docker logs forch-controller-1

echo DAQ log
cat $DAQBASE/inst/cmdrun.log

echo DAQ spot checks

# Basic process startup.
fgrep "Loading base module config" $DAQBASE/inst/cmdrun.log

# Testing that python path is good.
ls -l $DAQBASE/inst/daq.pid

# Requires valid config available.
cat $DAQBASE/inst/daq_run_id.txt

# Requiring mininet path.
ls -l $DAQBASE/inst/dp_port_acls.yaml

# Check that OVS switch connects properly to managed faucet.
fgrep "System port 1 on dpid 1 is active True" $DAQBASE/inst/cmdrun.log

echo Done with daq startup tests.

sleep 20

# Forch startup checks
# Check Forch has successfuly started
fgrep -o "Starting Forchestrator" $INST_BASE/forch.log | tee -a $TEST_RESULTS

yq '.dps."nz-kiwi-t2sw1".interfaces."1".native_vlan' $BEHAVIORAL_CONFIG | tee -a $TEST_RESULTS
yq '.dps."nz-kiwi-t2sw2".interfaces."1".native_vlan' $BEHAVIORAL_CONFIG | tee -a $TEST_RESULTS

# Start DHCP client on faux-1 and faux-2
docker exec forch-faux-1 dhclient -r &
docker exec forch-faux-2 dhclient -r
docker exec forch-faux-1 dhclient &
docker exec forch-faux-2 dhclient
docker exec forch-faux-1 ip addr show faux-eth0 | grep inet
docker exec forch-faux-2 ip addr show faux-eth0 | grep inet

vlan=$(yq '.dps."nz-kiwi-t2sw1".interfaces."1".native_vlan' $BEHAVIORAL_CONFIG)
echo $(( (vlan>271) + (vlan>276) )) | tee -a
vlan=$(yq '.dps."nz-kiwi-t2sw2".interfaces."1".native_vlan' $BEHAVIORAL_CONFIG)
echo $(( (vlan>271) + (vlan>276) )) | tee -a

# Waiting for DAQ test to complete
sleep 360

yq '.dps."nz-kiwi-t2sw1".interfaces."1".native_vlan' $BEHAVIORAL_CONFIG | tee -a $TEST_RESULTS
yq '.dps."nz-kiwi-t2sw2".interfaces."1".native_vlan' $BEHAVIORAL_CONFIG | tee -a $TEST_RESULTS
