#!/bin/bash -e

source bin/stack_functions

preamble_setup

export OUT_DIR
export TEST_RESULTS

# These two tests below could be run as their own test shards, if desired.
testing/test_solo
testing/test_counting
