#!/bin/bash -e

source bin/stack_functions

preamble_setup

export OUT_DIR
export TEST_RESULTS

testing/test_check
testing/test_topology
testing/test_flat
testing/test_solo
testing/test_counting
testing/python_test coverage test_faucetizer
testing/python_test coverage test_faucet_state_collector
testing/python_test coverage test_event
