#!/bin/bash

source bin/stack_functions

preamble_setup

echo Resetting stack to known state.
sudo ip link set t1sw1-eth28 up
sudo ip link set t1sw2-eth28 down
sleep 5
sudo ip link set t1sw2-eth28 up
sleep 25

echo Failover connectivity check | tee -a $TEST_RESULTS

docker exec forch-faux-1 ping -c 10 192.168.1.0 | tee $OUT_DIR/failscale1.log

docker exec forch-faux-1 ping -c 40 192.168.1.0 | tee $OUT_DIR/failscale2.log &
sleep 5
sudo ip link set t1sw1-eth28 down
wait

results1=$(fgrep icmp_seq $OUT_DIR/failscale1.log | wc -l)
results2=$(fgrep icmp_seq $OUT_DIR/failscale2.log | wc -l)

echo Found $results1 then $results2 results.

# Make sure there is some, but not too much, loss of connectivity.
echo Results $((results1 == 10)) $((results2 > 15 && results2 < 35)) | tee -a $TEST_RESULTS
