FROM ubuntu:20.04

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update
RUN apt install -y tzdata

RUN apt-get update && \
    apt-get install -y freeradius iproute2 vim sudo tcpdump iputils-ping

USER root

EXPOSE \
    1812/udp \
    1813/udp \
    18120

CMD ["freeradius", "-fxx", "-l", "stdout"]
