## Image name: forch/controller

FROM ubuntu:bionic

COPY bin/retry_cmd bin/

ENV AG="bin/retry_cmd apt-get -qqy --no-install-recommends -o=Dpkg::Use-Pty=0"

RUN $AG update && $AG install net-tools bash iproute2 iputils-ping tcpdump strace vim \
    jq nano ethtool netcat curl ifupdown isc-dhcp-client dnsmasq

# Weird workaround for problem running tcdump in a privlidged container.
RUN mv /usr/sbin/tcpdump /usr/bin/tcpdump

######## Everything above taken from faux device docker build file #####

WORKDIR /root
COPY bin/retry_cmd bin/
# Fake build running on CI while to avoid using venv during DAQ install.
ENV CI=true

RUN $AG update && $AG install ash iptables sudo openvswitch-switch openvswitch-common \
    python3 python3-pip python3.8 python3.8-venv python3.8-dev build-essential

RUN update-alternatives --install /usr/bin/python3 python /usr/bin/python3.8 2


COPY controller/bin/install_faucet bin/
COPY faucet/ faucet/
RUN bin/install_faucet && rm -rf faucet/.git

COPY controller/bin/install_forch bin/
COPY . forch/
RUN bin/install_forch && rm -rf forch/.git

COPY daq/ daq/
RUN daq/bin/setup_dev simple && rm -rf daq/.git

# Don't copy this earlier to optimize build.
COPY controller/bin bin/

CMD ["bin/controller_go"]
