## Image name: forch/faucet

FROM faucet/python3:5.0.1

RUN apk add -q tcpdump iptables sudo linux-headers build-base

COPY faucet/ /faucet-src/

# We don't need no stinkin' unit-tests...
RUN sed -i 's/.*unit.*//' /faucet-src/docker/install-faucet.sh

RUN /faucet-src/docker/install-faucet.sh && rm -rf /faucet-src/.git

# Check for target executable since installer doesn't error out properly.
RUN which faucet

COPY controller/bin/faucet_go bin/

CMD ["bin/faucet_go"]
