#!/bin/bash

echo Running faux $*

# Necessary to run dhclient in docker containers
umount /etc/resolv.conf 

declare -A options
for option in $*; do
    if [[ $option == *"="* ]]; then
	k=$(echo $option | cut -d'=' -f1)
        v=$(echo $option | cut -d'=' -f2)
        options[$k]=$v
    else
        options[$option]=$option
    fi
done

IFACE=faux-eth0
PREFIX=$(($FAUX_NUM/256 + 1))
SUFFIX=$(($FAUX_NUM%256))
IPADDR=192.168.$PREFIX.$SUFFIX
GATEWAY=192.168.1.0

while ! ip link show $IFACE; do
    sleep 2
done

echo Configuring network interface...
ip link
ip link set $IFACE up

if [ -n "${options[dhcp]}" ]; then
    echo Using DHCP...
    dhclient
else
    echo Statically assigning $IPADDR
    ip addr flush $IFACE
    ip addr add $IPADDR/16 dev $IFACE

    ip route add $IPADDR/16 via $GATEWAY dev $IFACE
    ip route add default via $GATEWAY
fi

if [ -n "${option[ping]}" ]; then
    ping -c 10 $GATEWAY &
fi

ip addr
ip route

if [ -n "${options[dnsmasq]}" ]; then
    echo Configuring dnsmasq...
    echo dhcp-range=192.168.1.10,192.168.1.255 >> /etc/dnsmasq.conf
    echo dhcp-host=$FAUX_MAC_PREFIX:8f:01,192.168.1.1 >> /etc/dnsmasq.conf
    echo dhcp-host=$FAUX_MAC_PREFIX:8f:02,192.168.1.2 >> /etc/dnsmasq.conf
    dnsmasq --log-facility=/tmp/dnsmasq.log --log-dhcp
fi

if [ -n "${options[http]}" ]; then
    echo Listening on TCP 8000...
    python3 -m http.server &
fi

echo Blocking for all eternity.
tail -f /dev/null
