# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: forch/proto/acl_state.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='forch/proto/acl_state.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1b\x66orch/proto/acl_state.proto\"\xb6\x01\n\x08\x41\x43LState\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\x05rules\x18\x02 \x03(\x0b\x32\x13.ACLState.RuleState\x1ax\n\tRuleState\x12\x18\n\x10rule_description\x18\x01 \x01(\t\x12\x14\n\x0cpacket_count\x18\x03 \x01(\x05\x12\x1d\n\x15interval_change_count\x18\x04 \x01(\x05\x12\x1c\n\x14interval_last_change\x18\x05 \x01(\tb\x06proto3'
)




_ACLSTATE_RULESTATE = _descriptor.Descriptor(
  name='RuleState',
  full_name='ACLState.RuleState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rule_description', full_name='ACLState.RuleState.rule_description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packet_count', full_name='ACLState.RuleState.packet_count', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interval_change_count', full_name='ACLState.RuleState.interval_change_count', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interval_last_change', full_name='ACLState.RuleState.interval_last_change', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=214,
)

_ACLSTATE = _descriptor.Descriptor(
  name='ACLState',
  full_name='ACLState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ACLState.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rules', full_name='ACLState.rules', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ACLSTATE_RULESTATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=214,
)

_ACLSTATE_RULESTATE.containing_type = _ACLSTATE
_ACLSTATE.fields_by_name['rules'].message_type = _ACLSTATE_RULESTATE
DESCRIPTOR.message_types_by_name['ACLState'] = _ACLSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ACLState = _reflection.GeneratedProtocolMessageType('ACLState', (_message.Message,), {

  'RuleState' : _reflection.GeneratedProtocolMessageType('RuleState', (_message.Message,), {
    'DESCRIPTOR' : _ACLSTATE_RULESTATE,
    '__module__' : 'forch.proto.acl_state_pb2'
    # @@protoc_insertion_point(class_scope:ACLState.RuleState)
    })
  ,
  'DESCRIPTOR' : _ACLSTATE,
  '__module__' : 'forch.proto.acl_state_pb2'
  # @@protoc_insertion_point(class_scope:ACLState)
  })
_sym_db.RegisterMessage(ACLState)
_sym_db.RegisterMessage(ACLState.RuleState)


# @@protoc_insertion_point(module_scope)
