# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: forch/proto/devices_state.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from forch.proto import shared_constants_pb2 as forch_dot_proto_dot_shared__constants__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='forch/proto/devices_state.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1f\x66orch/proto/devices_state.proto\x1a\"forch/proto/shared_constants.proto\"\x15\n\x06\x44\x65vice\x12\x0b\n\x03mac\x18\x01 \x01(\t\"L\n\x0f\x44\x65vicePortEvent\x12&\n\x05\x65vent\x18\x01 \x01(\x0e\x32\x17.PortBehavior.PortEvent\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"\xb4\x02\n\x0c\x44\x65vicesState\x12\x45\n\x15\x64\x65vice_mac_placements\x18\x01 \x03(\x0b\x32&.DevicesState.DeviceMacPlacementsEntry\x12\x43\n\x14\x64\x65vice_mac_behaviors\x18\x02 \x03(\x0b\x32%.DevicesState.DeviceMacBehaviorsEntry\x1aL\n\x18\x44\x65viceMacPlacementsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.DevicePlacement:\x02\x38\x01\x1aJ\n\x17\x44\x65viceMacBehaviorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.DeviceBehavior:\x02\x38\x01\"B\n\x0f\x44\x65vicePlacement\x12\x0e\n\x06switch\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x11\n\tconnected\x18\x03 \x01(\x08\"^\n\x0e\x44\x65viceBehavior\x12\x0f\n\x07segment\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12-\n\rport_behavior\x18\x03 \x01(\x0e\x32\x16.PortBehavior.Behavior\"\x8b\x01\n\x0fSegmentsToVlans\x12@\n\x11segments_to_vlans\x18\x01 \x03(\x0b\x32%.SegmentsToVlans.SegmentsToVlansEntry\x1a\x36\n\x14SegmentsToVlansEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[forch_dot_proto_dot_shared__constants__pb2.DESCRIPTOR,])




_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mac', full_name='Device.mac', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=92,
)


_DEVICEPORTEVENT = _descriptor.Descriptor(
  name='DevicePortEvent',
  full_name='DevicePortEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='DevicePortEvent.event', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='DevicePortEvent.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=170,
)


_DEVICESSTATE_DEVICEMACPLACEMENTSENTRY = _descriptor.Descriptor(
  name='DeviceMacPlacementsEntry',
  full_name='DevicesState.DeviceMacPlacementsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DevicesState.DeviceMacPlacementsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DevicesState.DeviceMacPlacementsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=405,
)

_DEVICESSTATE_DEVICEMACBEHAVIORSENTRY = _descriptor.Descriptor(
  name='DeviceMacBehaviorsEntry',
  full_name='DevicesState.DeviceMacBehaviorsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DevicesState.DeviceMacBehaviorsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DevicesState.DeviceMacBehaviorsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=481,
)

_DEVICESSTATE = _descriptor.Descriptor(
  name='DevicesState',
  full_name='DevicesState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_mac_placements', full_name='DevicesState.device_mac_placements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_mac_behaviors', full_name='DevicesState.device_mac_behaviors', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DEVICESSTATE_DEVICEMACPLACEMENTSENTRY, _DEVICESSTATE_DEVICEMACBEHAVIORSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=481,
)


_DEVICEPLACEMENT = _descriptor.Descriptor(
  name='DevicePlacement',
  full_name='DevicePlacement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='switch', full_name='DevicePlacement.switch', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='DevicePlacement.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connected', full_name='DevicePlacement.connected', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=549,
)


_DEVICEBEHAVIOR = _descriptor.Descriptor(
  name='DeviceBehavior',
  full_name='DeviceBehavior',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment', full_name='DeviceBehavior.segment', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='role', full_name='DeviceBehavior.role', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port_behavior', full_name='DeviceBehavior.port_behavior', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=645,
)


_SEGMENTSTOVLANS_SEGMENTSTOVLANSENTRY = _descriptor.Descriptor(
  name='SegmentsToVlansEntry',
  full_name='SegmentsToVlans.SegmentsToVlansEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='SegmentsToVlans.SegmentsToVlansEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='SegmentsToVlans.SegmentsToVlansEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=733,
  serialized_end=787,
)

_SEGMENTSTOVLANS = _descriptor.Descriptor(
  name='SegmentsToVlans',
  full_name='SegmentsToVlans',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='segments_to_vlans', full_name='SegmentsToVlans.segments_to_vlans', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SEGMENTSTOVLANS_SEGMENTSTOVLANSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=648,
  serialized_end=787,
)

_DEVICEPORTEVENT.fields_by_name['event'].enum_type = forch_dot_proto_dot_shared__constants__pb2._PORTBEHAVIOR_PORTEVENT
_DEVICESSTATE_DEVICEMACPLACEMENTSENTRY.fields_by_name['value'].message_type = _DEVICEPLACEMENT
_DEVICESSTATE_DEVICEMACPLACEMENTSENTRY.containing_type = _DEVICESSTATE
_DEVICESSTATE_DEVICEMACBEHAVIORSENTRY.fields_by_name['value'].message_type = _DEVICEBEHAVIOR
_DEVICESSTATE_DEVICEMACBEHAVIORSENTRY.containing_type = _DEVICESSTATE
_DEVICESSTATE.fields_by_name['device_mac_placements'].message_type = _DEVICESSTATE_DEVICEMACPLACEMENTSENTRY
_DEVICESSTATE.fields_by_name['device_mac_behaviors'].message_type = _DEVICESSTATE_DEVICEMACBEHAVIORSENTRY
_DEVICEBEHAVIOR.fields_by_name['port_behavior'].enum_type = forch_dot_proto_dot_shared__constants__pb2._PORTBEHAVIOR_BEHAVIOR
_SEGMENTSTOVLANS_SEGMENTSTOVLANSENTRY.containing_type = _SEGMENTSTOVLANS
_SEGMENTSTOVLANS.fields_by_name['segments_to_vlans'].message_type = _SEGMENTSTOVLANS_SEGMENTSTOVLANSENTRY
DESCRIPTOR.message_types_by_name['Device'] = _DEVICE
DESCRIPTOR.message_types_by_name['DevicePortEvent'] = _DEVICEPORTEVENT
DESCRIPTOR.message_types_by_name['DevicesState'] = _DEVICESSTATE
DESCRIPTOR.message_types_by_name['DevicePlacement'] = _DEVICEPLACEMENT
DESCRIPTOR.message_types_by_name['DeviceBehavior'] = _DEVICEBEHAVIOR
DESCRIPTOR.message_types_by_name['SegmentsToVlans'] = _SEGMENTSTOVLANS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), {
  'DESCRIPTOR' : _DEVICE,
  '__module__' : 'forch.proto.devices_state_pb2'
  # @@protoc_insertion_point(class_scope:Device)
  })
_sym_db.RegisterMessage(Device)

DevicePortEvent = _reflection.GeneratedProtocolMessageType('DevicePortEvent', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEPORTEVENT,
  '__module__' : 'forch.proto.devices_state_pb2'
  # @@protoc_insertion_point(class_scope:DevicePortEvent)
  })
_sym_db.RegisterMessage(DevicePortEvent)

DevicesState = _reflection.GeneratedProtocolMessageType('DevicesState', (_message.Message,), {

  'DeviceMacPlacementsEntry' : _reflection.GeneratedProtocolMessageType('DeviceMacPlacementsEntry', (_message.Message,), {
    'DESCRIPTOR' : _DEVICESSTATE_DEVICEMACPLACEMENTSENTRY,
    '__module__' : 'forch.proto.devices_state_pb2'
    # @@protoc_insertion_point(class_scope:DevicesState.DeviceMacPlacementsEntry)
    })
  ,

  'DeviceMacBehaviorsEntry' : _reflection.GeneratedProtocolMessageType('DeviceMacBehaviorsEntry', (_message.Message,), {
    'DESCRIPTOR' : _DEVICESSTATE_DEVICEMACBEHAVIORSENTRY,
    '__module__' : 'forch.proto.devices_state_pb2'
    # @@protoc_insertion_point(class_scope:DevicesState.DeviceMacBehaviorsEntry)
    })
  ,
  'DESCRIPTOR' : _DEVICESSTATE,
  '__module__' : 'forch.proto.devices_state_pb2'
  # @@protoc_insertion_point(class_scope:DevicesState)
  })
_sym_db.RegisterMessage(DevicesState)
_sym_db.RegisterMessage(DevicesState.DeviceMacPlacementsEntry)
_sym_db.RegisterMessage(DevicesState.DeviceMacBehaviorsEntry)

DevicePlacement = _reflection.GeneratedProtocolMessageType('DevicePlacement', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEPLACEMENT,
  '__module__' : 'forch.proto.devices_state_pb2'
  # @@protoc_insertion_point(class_scope:DevicePlacement)
  })
_sym_db.RegisterMessage(DevicePlacement)

DeviceBehavior = _reflection.GeneratedProtocolMessageType('DeviceBehavior', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEBEHAVIOR,
  '__module__' : 'forch.proto.devices_state_pb2'
  # @@protoc_insertion_point(class_scope:DeviceBehavior)
  })
_sym_db.RegisterMessage(DeviceBehavior)

SegmentsToVlans = _reflection.GeneratedProtocolMessageType('SegmentsToVlans', (_message.Message,), {

  'SegmentsToVlansEntry' : _reflection.GeneratedProtocolMessageType('SegmentsToVlansEntry', (_message.Message,), {
    'DESCRIPTOR' : _SEGMENTSTOVLANS_SEGMENTSTOVLANSENTRY,
    '__module__' : 'forch.proto.devices_state_pb2'
    # @@protoc_insertion_point(class_scope:SegmentsToVlans.SegmentsToVlansEntry)
    })
  ,
  'DESCRIPTOR' : _SEGMENTSTOVLANS,
  '__module__' : 'forch.proto.devices_state_pb2'
  # @@protoc_insertion_point(class_scope:SegmentsToVlans)
  })
_sym_db.RegisterMessage(SegmentsToVlans)
_sym_db.RegisterMessage(SegmentsToVlans.SegmentsToVlansEntry)


_DEVICESSTATE_DEVICEMACPLACEMENTSENTRY._options = None
_DEVICESSTATE_DEVICEMACBEHAVIORSENTRY._options = None
_SEGMENTSTOVLANS_SEGMENTSTOVLANSENTRY._options = None
# @@protoc_insertion_point(module_scope)
