# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: forch/proto/faucet_configuration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='forch/proto/faucet_configuration.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n&forch/proto/faucet_configuration.proto\"\xea\x01\n\x0c\x46\x61ucetConfig\x12#\n\x03\x64ps\x18\x01 \x03(\x0b\x32\x16.FaucetConfig.DpsEntry\x12\x0f\n\x07include\x18\x02 \x03(\t\x12\x0f\n\x07version\x18\x03 \x01(\x05\x12\'\n\x05vlans\x18\x04 \x03(\x0b\x32\x18.FaucetConfig.VlansEntry\x1a\x35\n\x08\x44psEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.Datapath:\x02\x38\x01\x1a\x33\n\nVlansEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x05value\x18\x02 \x01(\x0b\x32\x05.Vlan:\x02\x38\x01\"\xff\x01\n\x08\x44\x61tapath\x12\r\n\x05\x64p_id\x18\x01 \x01(\x05\x12\x15\n\rfaucet_dp_mac\x18\x02 \x01(\t\x12\x10\n\x08hardware\x18\x03 \x01(\t\x12\x14\n\x0clacp_timeout\x18\x04 \x01(\x05\x12\x15\n\x05stack\x18\x05 \x01(\x0b\x32\x06.Stack\x12-\n\ninterfaces\x18\x06 \x03(\x0b\x32\x19.Datapath.InterfacesEntry\x12 \n\x0blldp_beacon\x18\x07 \x01(\x0b\x32\x0b.LLDPBeacon\x1a=\n\x0fInterfacesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.Interface:\x02\x38\x01\"\x19\n\x05Stack\x12\x10\n\x08priority\x18\x01 \x01(\x05\"=\n\nLLDPBeacon\x12\x18\n\x10max_per_interval\x18\x01 \x01(\x05\x12\x15\n\rsend_interval\x18\x02 \x01(\x05\"\x97\x01\n\tInterface\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x19\n\x05stack\x18\x02 \x01(\x0b\x32\n.StackLink\x12\x0c\n\x04lacp\x18\x03 \x01(\x05\x12\x14\n\x0ctagged_vlans\x18\x04 \x03(\x05\x12\x13\n\x0bnative_vlan\x18\x05 \x01(\x05\x12\x0e\n\x06\x61\x63l_in\x18\x06 \x01(\t\x12\x11\n\tmax_hosts\x18\x07 \x01(\x05\"\x1b\n\x04Vlan\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\"%\n\tStackLink\x12\n\n\x02\x64p\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FAUCETCONFIG_DPSENTRY = _descriptor.Descriptor(
  name='DpsEntry',
  full_name='FaucetConfig.DpsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='FaucetConfig.DpsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='FaucetConfig.DpsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=224,
)

_FAUCETCONFIG_VLANSENTRY = _descriptor.Descriptor(
  name='VlansEntry',
  full_name='FaucetConfig.VlansEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='FaucetConfig.VlansEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='FaucetConfig.VlansEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=277,
)

_FAUCETCONFIG = _descriptor.Descriptor(
  name='FaucetConfig',
  full_name='FaucetConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dps', full_name='FaucetConfig.dps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='include', full_name='FaucetConfig.include', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='FaucetConfig.version', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vlans', full_name='FaucetConfig.vlans', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FAUCETCONFIG_DPSENTRY, _FAUCETCONFIG_VLANSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=277,
)


_DATAPATH_INTERFACESENTRY = _descriptor.Descriptor(
  name='InterfacesEntry',
  full_name='Datapath.InterfacesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Datapath.InterfacesEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Datapath.InterfacesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=535,
)

_DATAPATH = _descriptor.Descriptor(
  name='Datapath',
  full_name='Datapath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dp_id', full_name='Datapath.dp_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='faucet_dp_mac', full_name='Datapath.faucet_dp_mac', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hardware', full_name='Datapath.hardware', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lacp_timeout', full_name='Datapath.lacp_timeout', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stack', full_name='Datapath.stack', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interfaces', full_name='Datapath.interfaces', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lldp_beacon', full_name='Datapath.lldp_beacon', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATAPATH_INTERFACESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=535,
)


_STACK = _descriptor.Descriptor(
  name='Stack',
  full_name='Stack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='priority', full_name='Stack.priority', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=537,
  serialized_end=562,
)


_LLDPBEACON = _descriptor.Descriptor(
  name='LLDPBeacon',
  full_name='LLDPBeacon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_per_interval', full_name='LLDPBeacon.max_per_interval', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='send_interval', full_name='LLDPBeacon.send_interval', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=564,
  serialized_end=625,
)


_INTERFACE = _descriptor.Descriptor(
  name='Interface',
  full_name='Interface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='Interface.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stack', full_name='Interface.stack', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lacp', full_name='Interface.lacp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tagged_vlans', full_name='Interface.tagged_vlans', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='native_vlan', full_name='Interface.native_vlan', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acl_in', full_name='Interface.acl_in', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_hosts', full_name='Interface.max_hosts', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=628,
  serialized_end=779,
)


_VLAN = _descriptor.Descriptor(
  name='Vlan',
  full_name='Vlan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='Vlan.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=781,
  serialized_end=808,
)


_STACKLINK = _descriptor.Descriptor(
  name='StackLink',
  full_name='StackLink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dp', full_name='StackLink.dp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='StackLink.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=810,
  serialized_end=847,
)

_FAUCETCONFIG_DPSENTRY.fields_by_name['value'].message_type = _DATAPATH
_FAUCETCONFIG_DPSENTRY.containing_type = _FAUCETCONFIG
_FAUCETCONFIG_VLANSENTRY.fields_by_name['value'].message_type = _VLAN
_FAUCETCONFIG_VLANSENTRY.containing_type = _FAUCETCONFIG
_FAUCETCONFIG.fields_by_name['dps'].message_type = _FAUCETCONFIG_DPSENTRY
_FAUCETCONFIG.fields_by_name['vlans'].message_type = _FAUCETCONFIG_VLANSENTRY
_DATAPATH_INTERFACESENTRY.fields_by_name['value'].message_type = _INTERFACE
_DATAPATH_INTERFACESENTRY.containing_type = _DATAPATH
_DATAPATH.fields_by_name['stack'].message_type = _STACK
_DATAPATH.fields_by_name['interfaces'].message_type = _DATAPATH_INTERFACESENTRY
_DATAPATH.fields_by_name['lldp_beacon'].message_type = _LLDPBEACON
_INTERFACE.fields_by_name['stack'].message_type = _STACKLINK
DESCRIPTOR.message_types_by_name['FaucetConfig'] = _FAUCETCONFIG
DESCRIPTOR.message_types_by_name['Datapath'] = _DATAPATH
DESCRIPTOR.message_types_by_name['Stack'] = _STACK
DESCRIPTOR.message_types_by_name['LLDPBeacon'] = _LLDPBEACON
DESCRIPTOR.message_types_by_name['Interface'] = _INTERFACE
DESCRIPTOR.message_types_by_name['Vlan'] = _VLAN
DESCRIPTOR.message_types_by_name['StackLink'] = _STACKLINK

FaucetConfig = _reflection.GeneratedProtocolMessageType('FaucetConfig', (_message.Message,), dict(

  DpsEntry = _reflection.GeneratedProtocolMessageType('DpsEntry', (_message.Message,), dict(
    DESCRIPTOR = _FAUCETCONFIG_DPSENTRY,
    __module__ = 'forch.proto.faucet_configuration_pb2'
    # @@protoc_insertion_point(class_scope:FaucetConfig.DpsEntry)
    ))
  ,

  VlansEntry = _reflection.GeneratedProtocolMessageType('VlansEntry', (_message.Message,), dict(
    DESCRIPTOR = _FAUCETCONFIG_VLANSENTRY,
    __module__ = 'forch.proto.faucet_configuration_pb2'
    # @@protoc_insertion_point(class_scope:FaucetConfig.VlansEntry)
    ))
  ,
  DESCRIPTOR = _FAUCETCONFIG,
  __module__ = 'forch.proto.faucet_configuration_pb2'
  # @@protoc_insertion_point(class_scope:FaucetConfig)
  ))
_sym_db.RegisterMessage(FaucetConfig)
_sym_db.RegisterMessage(FaucetConfig.DpsEntry)
_sym_db.RegisterMessage(FaucetConfig.VlansEntry)

Datapath = _reflection.GeneratedProtocolMessageType('Datapath', (_message.Message,), dict(

  InterfacesEntry = _reflection.GeneratedProtocolMessageType('InterfacesEntry', (_message.Message,), dict(
    DESCRIPTOR = _DATAPATH_INTERFACESENTRY,
    __module__ = 'forch.proto.faucet_configuration_pb2'
    # @@protoc_insertion_point(class_scope:Datapath.InterfacesEntry)
    ))
  ,
  DESCRIPTOR = _DATAPATH,
  __module__ = 'forch.proto.faucet_configuration_pb2'
  # @@protoc_insertion_point(class_scope:Datapath)
  ))
_sym_db.RegisterMessage(Datapath)
_sym_db.RegisterMessage(Datapath.InterfacesEntry)

Stack = _reflection.GeneratedProtocolMessageType('Stack', (_message.Message,), dict(
  DESCRIPTOR = _STACK,
  __module__ = 'forch.proto.faucet_configuration_pb2'
  # @@protoc_insertion_point(class_scope:Stack)
  ))
_sym_db.RegisterMessage(Stack)

LLDPBeacon = _reflection.GeneratedProtocolMessageType('LLDPBeacon', (_message.Message,), dict(
  DESCRIPTOR = _LLDPBEACON,
  __module__ = 'forch.proto.faucet_configuration_pb2'
  # @@protoc_insertion_point(class_scope:LLDPBeacon)
  ))
_sym_db.RegisterMessage(LLDPBeacon)

Interface = _reflection.GeneratedProtocolMessageType('Interface', (_message.Message,), dict(
  DESCRIPTOR = _INTERFACE,
  __module__ = 'forch.proto.faucet_configuration_pb2'
  # @@protoc_insertion_point(class_scope:Interface)
  ))
_sym_db.RegisterMessage(Interface)

Vlan = _reflection.GeneratedProtocolMessageType('Vlan', (_message.Message,), dict(
  DESCRIPTOR = _VLAN,
  __module__ = 'forch.proto.faucet_configuration_pb2'
  # @@protoc_insertion_point(class_scope:Vlan)
  ))
_sym_db.RegisterMessage(Vlan)

StackLink = _reflection.GeneratedProtocolMessageType('StackLink', (_message.Message,), dict(
  DESCRIPTOR = _STACKLINK,
  __module__ = 'forch.proto.faucet_configuration_pb2'
  # @@protoc_insertion_point(class_scope:StackLink)
  ))
_sym_db.RegisterMessage(StackLink)


_FAUCETCONFIG_DPSENTRY.has_options = True
_FAUCETCONFIG_DPSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_FAUCETCONFIG_VLANSENTRY.has_options = True
_FAUCETCONFIG_VLANSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_DATAPATH_INTERFACESENTRY.has_options = True
_DATAPATH_INTERFACESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
