# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: forch/proto/network_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='forch/proto/network_state.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1f\x66orch/proto/network_state.proto\"\xb1\x02\n\x0c\x44\x65vicesState\x12\x43\n\x14\x64\x65vice_mac_learnings\x18\x01 \x03(\x0b\x32%.DevicesState.DeviceMacLearningsEntry\x12\x43\n\x14\x64\x65vice_mac_behaviors\x18\x02 \x03(\x0b\x32%.DevicesState.DeviceMacBehaviorsEntry\x1aK\n\x17\x44\x65viceMacLearningsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.DevicePlacement:\x02\x38\x01\x1aJ\n\x17\x44\x65viceMacBehaviorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.DeviceBehavior:\x02\x38\x01\"P\n\x06\x44\x65vice\x12#\n\tplacement\x18\x01 \x01(\x0b\x32\x10.DevicePlacement\x12!\n\x08\x62\x65havior\x18\x02 \x01(\x0b\x32\x0f.DeviceBehavior\"B\n\x0f\x44\x65vicePlacement\x12\x0e\n\x06switch\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x11\n\tconnected\x18\x03 \x01(\x08\"+\n\x0e\x44\x65viceBehavior\x12\x0b\n\x03vid\x18\x01 \x01(\x05\x12\x0c\n\x04role\x18\x02 \x01(\t\"\xb6\x01\n\tMatchRule\x12\x10\n\x08\x65th_type\x18\x01 \x01(\x05\x12\x0f\n\x07\x65th_dst\x18\x02 \x01(\t\x12\x10\n\x08ip_proto\x18\x03 \x01(\x05\x12\x0e\n\x06ip_dst\x18\x04 \x01(\t\x12\x10\n\x08src_port\x18\x05 \x01(\x05\x12\x10\n\x08\x64st_port\x18\x06 \x01(\x05\x12!\n\x06\x61\x63tion\x18\x07 \x01(\x0e\x32\x11.MatchRule.Action\"\x1d\n\x06\x41\x63tion\x12\x08\n\x04\x44\x45NY\x10\x00\x12\t\n\x05\x41LLOW\x10\x01\x62\x06proto3')
)



_MATCHRULE_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='MatchRule.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DENY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALLOW', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=692,
  serialized_end=721,
)
_sym_db.RegisterEnumDescriptor(_MATCHRULE_ACTION)


_DEVICESSTATE_DEVICEMACLEARNINGSENTRY = _descriptor.Descriptor(
  name='DeviceMacLearningsEntry',
  full_name='DevicesState.DeviceMacLearningsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DevicesState.DeviceMacLearningsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='DevicesState.DeviceMacLearningsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=265,
)

_DEVICESSTATE_DEVICEMACBEHAVIORSENTRY = _descriptor.Descriptor(
  name='DeviceMacBehaviorsEntry',
  full_name='DevicesState.DeviceMacBehaviorsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DevicesState.DeviceMacBehaviorsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='DevicesState.DeviceMacBehaviorsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=341,
)

_DEVICESSTATE = _descriptor.Descriptor(
  name='DevicesState',
  full_name='DevicesState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_mac_learnings', full_name='DevicesState.device_mac_learnings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_mac_behaviors', full_name='DevicesState.device_mac_behaviors', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DEVICESSTATE_DEVICEMACLEARNINGSENTRY, _DEVICESSTATE_DEVICEMACBEHAVIORSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=341,
)


_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='placement', full_name='Device.placement', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='behavior', full_name='Device.behavior', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=423,
)


_DEVICEPLACEMENT = _descriptor.Descriptor(
  name='DevicePlacement',
  full_name='DevicePlacement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='switch', full_name='DevicePlacement.switch', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='DevicePlacement.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connected', full_name='DevicePlacement.connected', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=491,
)


_DEVICEBEHAVIOR = _descriptor.Descriptor(
  name='DeviceBehavior',
  full_name='DeviceBehavior',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vid', full_name='DeviceBehavior.vid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='DeviceBehavior.role', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=536,
)


_MATCHRULE = _descriptor.Descriptor(
  name='MatchRule',
  full_name='MatchRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eth_type', full_name='MatchRule.eth_type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eth_dst', full_name='MatchRule.eth_dst', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_proto', full_name='MatchRule.ip_proto', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_dst', full_name='MatchRule.ip_dst', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src_port', full_name='MatchRule.src_port', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_port', full_name='MatchRule.dst_port', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='MatchRule.action', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MATCHRULE_ACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=721,
)

_DEVICESSTATE_DEVICEMACLEARNINGSENTRY.fields_by_name['value'].message_type = _DEVICEPLACEMENT
_DEVICESSTATE_DEVICEMACLEARNINGSENTRY.containing_type = _DEVICESSTATE
_DEVICESSTATE_DEVICEMACBEHAVIORSENTRY.fields_by_name['value'].message_type = _DEVICEBEHAVIOR
_DEVICESSTATE_DEVICEMACBEHAVIORSENTRY.containing_type = _DEVICESSTATE
_DEVICESSTATE.fields_by_name['device_mac_learnings'].message_type = _DEVICESSTATE_DEVICEMACLEARNINGSENTRY
_DEVICESSTATE.fields_by_name['device_mac_behaviors'].message_type = _DEVICESSTATE_DEVICEMACBEHAVIORSENTRY
_DEVICE.fields_by_name['placement'].message_type = _DEVICEPLACEMENT
_DEVICE.fields_by_name['behavior'].message_type = _DEVICEBEHAVIOR
_MATCHRULE.fields_by_name['action'].enum_type = _MATCHRULE_ACTION
_MATCHRULE_ACTION.containing_type = _MATCHRULE
DESCRIPTOR.message_types_by_name['DevicesState'] = _DEVICESSTATE
DESCRIPTOR.message_types_by_name['Device'] = _DEVICE
DESCRIPTOR.message_types_by_name['DevicePlacement'] = _DEVICEPLACEMENT
DESCRIPTOR.message_types_by_name['DeviceBehavior'] = _DEVICEBEHAVIOR
DESCRIPTOR.message_types_by_name['MatchRule'] = _MATCHRULE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DevicesState = _reflection.GeneratedProtocolMessageType('DevicesState', (_message.Message,), dict(

  DeviceMacLearningsEntry = _reflection.GeneratedProtocolMessageType('DeviceMacLearningsEntry', (_message.Message,), dict(
    DESCRIPTOR = _DEVICESSTATE_DEVICEMACLEARNINGSENTRY,
    __module__ = 'forch.proto.network_state_pb2'
    # @@protoc_insertion_point(class_scope:DevicesState.DeviceMacLearningsEntry)
    ))
  ,

  DeviceMacBehaviorsEntry = _reflection.GeneratedProtocolMessageType('DeviceMacBehaviorsEntry', (_message.Message,), dict(
    DESCRIPTOR = _DEVICESSTATE_DEVICEMACBEHAVIORSENTRY,
    __module__ = 'forch.proto.network_state_pb2'
    # @@protoc_insertion_point(class_scope:DevicesState.DeviceMacBehaviorsEntry)
    ))
  ,
  DESCRIPTOR = _DEVICESSTATE,
  __module__ = 'forch.proto.network_state_pb2'
  # @@protoc_insertion_point(class_scope:DevicesState)
  ))
_sym_db.RegisterMessage(DevicesState)
_sym_db.RegisterMessage(DevicesState.DeviceMacLearningsEntry)
_sym_db.RegisterMessage(DevicesState.DeviceMacBehaviorsEntry)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), dict(
  DESCRIPTOR = _DEVICE,
  __module__ = 'forch.proto.network_state_pb2'
  # @@protoc_insertion_point(class_scope:Device)
  ))
_sym_db.RegisterMessage(Device)

DevicePlacement = _reflection.GeneratedProtocolMessageType('DevicePlacement', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEPLACEMENT,
  __module__ = 'forch.proto.network_state_pb2'
  # @@protoc_insertion_point(class_scope:DevicePlacement)
  ))
_sym_db.RegisterMessage(DevicePlacement)

DeviceBehavior = _reflection.GeneratedProtocolMessageType('DeviceBehavior', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEBEHAVIOR,
  __module__ = 'forch.proto.network_state_pb2'
  # @@protoc_insertion_point(class_scope:DeviceBehavior)
  ))
_sym_db.RegisterMessage(DeviceBehavior)

MatchRule = _reflection.GeneratedProtocolMessageType('MatchRule', (_message.Message,), dict(
  DESCRIPTOR = _MATCHRULE,
  __module__ = 'forch.proto.network_state_pb2'
  # @@protoc_insertion_point(class_scope:MatchRule)
  ))
_sym_db.RegisterMessage(MatchRule)


_DEVICESSTATE_DEVICEMACLEARNINGSENTRY._options = None
_DEVICESSTATE_DEVICEMACBEHAVIORSENTRY._options = None
# @@protoc_insertion_point(module_scope)
